from pathlib import Path

BASE_DIR = Path("/opt/pump_station")
DATA_DIR = BASE_DIR / "data"
LOG_DIR = BASE_DIR / "logs"
EXPORT_DIR = BASE_DIR / "exports"

DB_PATH = DATA_DIR / "main.db"
BACKUP_A_PATH = DATA_DIR / "main_backup_a.db"
BACKUP_B_PATH = DATA_DIR / "main_backup_b.db"

PLC_IP = "192.168.117.10"
PLC_RACK = 0
PLC_SLOT = 1

MV210_IP = "192.168.117.45"
MV210_PORT = 502
MV210_UNIT = 1

TIMEZONE_OFFSET_MINUTES = 300  # UTC+5

WAIT_POLL_SECONDS = 5
BOARD_LOG_INTERVAL_WAIT = 30
BOARD_LOG_INTERVAL_REC = 30
WORK_LOG_INTERVAL_REC = 1

DB_COMMIT_INTERVAL_SECONDS = 60
TIME_SYNC_INTERVAL_SECONDS = 600
BACKUP_INTERVAL_REC_SECONDS = 600
USB_EXPORT_CHECK_INTERVAL_SECONDS = 15

MANIFOLD_START_THRESHOLD_MPA = 1.0
MANIFOLD_STOP_THRESHOLD_MPA = 1.0
CARDAN_ACTIVITY_THRESHOLD = 1
RETURN_TO_WAIT_DELAY_SECONDS = 60

CARDAN_PULSES_PER_REV = 1.0
GEAR_RATIO = 4.61
ENGINE_RPM_FROM_CARDAN_COEFF = 7.63
PUMP_LITERS_PER_REV = 4.691

PERIOD_WINDOW_SIZE = 3
COUNTER_STALL_WINDOW = 3
SMART_UPDATE_INTERVAL_SECONDS = 5

DB1_OFFSET_20 = ("REAL", 1, 20)
DB2_OFFSET_20 = ("REAL", 2, 20)
DB3_OFFSET_20 = ("REAL", 3, 20)
DB6_OFFSET_20 = ("REAL", 6, 20)
DB8_OFFSET_20 = ("REAL", 8, 20)
DB9_OFFSET_20 = ("REAL", 9, 20)

MV210_DI1_COUNTER_ADDR = 160
MV210_DI3_PERIOD_ADDR = 164

USB_MOUNT_POINT = "/media/usb_export"
USB_AUTO_UNMOUNT_AFTER_EXPORT = True
